alias taz="az account show"
alias ti="terraform init"
alias tp="terraform plan"
alias ta="terraform apply -auto-approve"
alias td="terraform destroy -auto-approve"
alias to="terraform output"
alias tc="terraform console"
alias tt="terraform plan"
alias tt2="terraform plan -var var_string=eri -var var_number=77"
alias tv="terraform validate"
alias tf="terraform fmt"
alias ts="terraform state list"